#!/bin/bash
mkdir ~/.BackgroundChanger/
rm 2880x1800.png
wget -O ~/.BackgroundChanger/1.png --show-progress https://source.unsplash.com/random/2880x1800.png 
feh --bg-scale ~/.BackgroundChanger/1.png
